# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
install: travis_wait 40 mvn install

r_packages:
  - covr

after_success:
  - Rscript -e 'library(covr); codecov()'
